In [1]:
%load_ext autoreload
%autoreload 2
# %env CUDA_VISIBLE_DEVICES=0

In [2]:
from stats_utils import *
import pandas as pd
import os

In [ ]:
CLEANED_FILE = 'areds_cleaned.csv'
LOG_DIR = 'log_dir'

In [4]:
raw = pd.read_csv(os.path.join(LOG_DIR, f"{CLEANED_FILE}"))
print(raw.shape)
raw.head(1)

(1260, 83)

,Name,State,Notes,User,Tags,Created,Runtime,Sweep,backbone_model_str,batch_size,...,Job Type,Updated,End Time,Hostname,Description,Commit,GitHub,GPU Count,GPU Type,model_family
0,testrun_False_FE_False_100_linear_2026-06-15_1...,finished,-,NaN,NaN,2026-06-15T14:08:16.000Z,5317,NaN,simclr_inet_nako,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SSL

In [ ]:
freeze_encoder = 1
surv_head = 'mlp'
df_fr = prepare_df(raw, freeze_encoder=freeze_encoder)
table4_min_training_size(df_fr, freeze_encoder, surv_head=surv_head, table_number=4)

Protocol: frozen (freeze_encoder=1)
Rows after filtering : 630
Models               : ['dino_meta', 'dino_nako', 'nako_mae', 'nako_mae_scr', 'resnet_imagenet', 'retfound', 'scratch', 'simclr_inet_nako', 'simclr_nako']
No nulls found.
All conditions have 5 seeds.
  Saved table4_min_training_size_mlp_freeze.csv / .txt

,Model,Family,Min n (CI lower≥0.75),Min n (CI lower≥95% peak),Peak C-index [95% CI]
0,MAE-NAKO-ImageNet,SSL,≤500,"≤10,000","0.876 [0.876, 0.877]"
1,MAE-NAKO,SSL,"≤1,000","≤10,000","0.846 [0.833, 0.856]"
2,SimCLR-INet-NAKO,SSL,≤100,≤500,"0.920 [0.919, 0.921]"
3,SimCLR-NAKO,SSL,≤100,≤500,"0.913 [0.906, 0.918]"
4,RETFound,FM,≤500,"≤10,000","0.877 [0.872, 0.881]"
5,DINOv2-NAKO,FM,≤100,"≤1,000","0.914 [0.912, 0.916]"
6,DINOv2-Meta,FM,≤100,"≤1,000","0.916 [0.915, 0.917]"
7,ResNet-ImageNet,Supervised,"≤10,000","≤10,000","0.810 [0.792, 0.828]"
8,ResNet-Scratch,Supervised,">32,500","≤10,000","0.675 [0.639, 0.715]"

In [ ]:
freeze_encoder = 0
surv_head = 'mlp'
df_fr = prepare_df(raw, freeze_encoder=freeze_encoder)
table4_min_training_size(df_fr, freeze_encoder, surv_head=surv_head, table_number=6)

Protocol: fine-tuned (freeze_encoder=0)
Rows after filtering : 630
Models               : ['dino_meta', 'dino_nako', 'nako_mae', 'nako_mae_scr', 'resnet_imagenet', 'retfound', 'scratch', 'simclr_inet_nako', 'simclr_nako']
No nulls found.
All conditions have 5 seeds.
  Saved table4_min_training_size_mlp_fine-tune.csv / .txt

,Model,Family,Min n (CI lower≥0.75),Min n (CI lower≥95% peak),Peak C-index [95% CI]
0,MAE-NAKO-ImageNet,SSL,≤100,"≤1,000","0.929 [0.928, 0.930]"
1,MAE-NAKO,SSL,≤500,"≤10,000","0.918 [0.917, 0.920]"
2,SimCLR-INet-NAKO,SSL,≤500,"≤1,000","0.931 [0.929, 0.932]"
3,SimCLR-NAKO,SSL,≤500,"≤10,000","0.933 [0.932, 0.935]"
4,RETFound,FM,≤500,"≤1,000","0.930 [0.929, 0.932]"
5,DINOv2-NAKO,FM,"≤10,000","≤10,000","0.908 [0.906, 0.911]"
6,DINOv2-Meta,FM,"≤10,000","≤10,000","0.911 [0.909, 0.913]"
7,ResNet-ImageNet,Supervised,≤500,"≤10,000","0.932 [0.930, 0.933]"
8,ResNet-Scratch,Supervised,"≤10,000","≤10,000","0.927 [0.925, 0.928]"

In [ ]:
freeze_encoder = 1
surv_head = 'linear'
df_fr = prepare_df(raw, freeze_encoder=freeze_encoder)
table4_min_training_size(df_fr, freeze_encoder, surv_head=surv_head,  table_number=5)

Protocol: frozen (freeze_encoder=1)
Rows after filtering : 630
Models               : ['dino_meta', 'dino_nako', 'nako_mae', 'nako_mae_scr', 'resnet_imagenet', 'retfound', 'scratch', 'simclr_inet_nako', 'simclr_nako']
No nulls found.
All conditions have 5 seeds.
  Saved table4_min_training_size_linear_freeze.csv / .txt

,Model,Family,Min n (CI lower≥0.75),Min n (CI lower≥95% peak),Peak C-index [95% CI]
0,MAE-NAKO-ImageNet,SSL,≤500,"≤10,000","0.830 [0.829, 0.831]"
1,MAE-NAKO,SSL,"≤10,000","≤10,000","0.826 [0.824, 0.829]"
2,SimCLR-INet-NAKO,SSL,≤100,≤100,"0.893 [0.893, 0.893]"
3,SimCLR-NAKO,SSL,≤100,≤100,"0.889 [0.889, 0.889]"
4,RETFound,FM,"≤1,000","≤10,000","0.860 [0.858, 0.862]"
5,DINOv2-NAKO,FM,≤100,≤500,"0.913 [0.913, 0.914]"
6,DINOv2-Meta,FM,≤100,≤500,"0.912 [0.911, 0.914]"
7,ResNet-ImageNet,Supervised,"≤20,000","≤10,000","0.777 [0.764, 0.786]"
8,ResNet-Scratch,Supervised,">32,500","≤30,000","0.754 [0.735, 0.769]"

In [ ]:
freeze_encoder = 0
surv_head = 'linear'
df_fr = prepare_df(raw, freeze_encoder=freeze_encoder)
table4_min_training_size(df_fr, freeze_encoder, surv_head=surv_head , table_number=7)

Protocol: fine-tuned (freeze_encoder=0)
Rows after filtering : 630
Models               : ['dino_meta', 'dino_nako', 'nako_mae', 'nako_mae_scr', 'resnet_imagenet', 'retfound', 'scratch', 'simclr_inet_nako', 'simclr_nako']
No nulls found.
All conditions have 5 seeds.
  Saved table4_min_training_size_linear_fine-tune.csv / .txt

,Model,Family,Min n (CI lower≥0.75),Min n (CI lower≥95% peak),Peak C-index [95% CI]
0,MAE-NAKO-ImageNet,SSL,≤100,"≤1,000","0.928 [0.927, 0.929]"
1,MAE-NAKO,SSL,≤500,"≤10,000","0.918 [0.917, 0.920]"
2,SimCLR-INet-NAKO,SSL,≤100,"≤1,000","0.930 [0.929, 0.932]"
3,SimCLR-NAKO,SSL,≤500,"≤1,000","0.932 [0.930, 0.933]"
4,RETFound,FM,≤100,≤500,"0.932 [0.928, 0.934]"
5,DINOv2-NAKO,FM,"≤10,000","≤10,000","0.913 [0.912, 0.914]"
6,DINOv2-Meta,FM,"≤10,000","≤10,000","0.912 [0.910, 0.914]"
7,ResNet-ImageNet,Supervised,≤500,"≤10,000","0.930 [0.928, 0.931]"
8,ResNet-Scratch,Supervised,"≤1,000","≤10,000","0.928 [0.927, 0.930]"